// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2LPPbgorKZWNMJJquXipcxpiX-7Zuj-Q',
    //apiKey: 'AIzaSyC54wRiRLKn35RJGfGOpOEXZs8bSSCRr9M',
    appId: '1:722175254039:web:03239cf2907bce5f44c652',
    messagingSenderId: '722175254039',
    projectId: 'yep-firebase-project',
    authDomain: 'yep-firebase-project.firebaseapp.com',
    storageBucket: 'yep-firebase-project.appspot.com',
    measurementId: 'G-W8JHQL3EPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LPPbgorKZWNMJJquXipcxpiX-7Zuj-Q',
    appId: '1:722175254039:android:a3b6559ff8a6e2b644c652',
    messagingSenderId: '722175254039',
    projectId: 'yep-firebase-project',
    storageBucket: 'yep-firebase-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoAEYbFy6PJdfMOUL6THpfSDMiaJKHK74',
    appId: '1:722175254039:ios:9f482f61fb83c33c44c652',
    messagingSenderId: '722175254039',
    projectId: 'yep-firebase-project',
    storageBucket: 'yep-firebase-project.appspot.com',
    iosClientId:
        '722175254039-oat5v6bh3mdtt8rmttrrqrpg4ukott7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.yepProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoAEYbFy6PJdfMOUL6THpfSDMiaJKHK74',
    appId: '1:722175254039:ios:2986717c627be97244c652',
    messagingSenderId: '722175254039',
    projectId: 'yep-firebase-project',
    storageBucket: 'yep-firebase-project.appspot.com',
    iosClientId:
        '722175254039-1j5gop42hmnoa51o8iceicfgmhbhnhhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.yepProject.RunnerTests',
  );
}
